Backend: Thumbnail generation
Teknologforeningen/fotogalleri pull request #3
Opened 2019-08-10 20:32 UTC by rosasam

Add code for generating thumbnails from an image file. Thumnbails are saved as jgp:s.

2019-08-11 23:13 UTC, c00k133 requested changes

2019-08-11 23:13 UTC, c00k133 commented on fotogalleri/backend/thumbnail_utils.py
> +    rgb_image.save(img_path + name + ".jpg", format="JPEG")
Do we check whether an image at `img_path` already exists? In case the caller should handle this a comment would be nice.

2019-08-15 17:08 UTC, c00k133 requested changes

2019-08-15 17:08 UTC, c00k133 commented on fotogalleri/backend/thumbnail_utils.py
> +    name += f"{w}x{h}"
This kind of string interpolation is only available in Python 3.7, but unfortunately we are still running 3.5.2 on the server. Best to keep it backwards compatible until we are able to update.

2019-08-15 17:24 UTC, c00k133 commented on fotogalleri/backend/thumbnail_utils.py
> +    rgb_image.save(img_path + name + ".jpg", format="JPEG")
Additionally, should programmatically check whether the extension already exists in the name?

2019-08-15 22:51 UTC, c00k133 commented on fotogalleri/backend/thumbnail_utils.py
> +    rgb_image.save(img_path + name + ".jpg", format="JPEG")
We could also utilize `os.path.join(..)` for concatenating path strings to be sure they go right

2019-08-21 20:15 UTC, rosasam commented on fotogalleri/backend/thumbnail_utils.py
> +    rgb_image.save(img_path + name + ".jpg", format="JPEG")
We should probably use os.path.join in the future, for now I'd leave it as is, and implement it once we see how we're actually going to save the thumbnails.

2019-08-25 20:42 UTC, c00k133 approved these changes
+1

2019-08-25 20:43 UTC, c00k133 commented
Should we delete the test images?

2019-09-13 11:40 UTC, rosasam commented
nah

2019-09-13 11:41 UTC, merged